import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/component/header";
import Footer from "@/component/footer";
import { Suspense } from "react";
import NavEvent from "@/component/nav-event";
import NavFallback from "@/component/nav-event/nav-fallback";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer/>
        <Suspense fallback={<NavFallback/>}>
          <NavEvent/>
        </Suspense>
      </body>
    </html>
  );
}
